name: Makefile CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # 当推送的标签匹配v*时触发（如v1.0.0）
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC and G++
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++

      - name: Install ncurses
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev

      - name: Build project
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: ./mygame

  create-release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # 仅在标签推送时运行
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: executable
          path: ./dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/mygame
          asset_name: mygame
          asset_content_type: application/octet-stream
