name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install GCC and G++
      run:
        sudo apt-get update &&
        sudo apt-get install -y gcc g++

    - name: Install ncurses
      run:
        sudo apt-get update &&
        sudo apt-get install -y libncurses-dev

    - name: build
      run: make
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: ./mygame
